server:
  port: 8080

spring:

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aaaicu.iptime.org:13305/spiritual_war?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: aaaicu
    password: dk2cka!!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

  output:
    ansi:
      enabled: always

  # 스웨거 3.0.0 업데이트 후 spring 2.6 버전 호환 불가
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
      
logging:
  level:
    org.hibernate.type: trace


