server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/spiritual_war?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: aaaicu
    password: dk2cka!!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true


      
      